version: "3.9"
services:
  web:
    build: .
    container_name: viceversa-gianpaolo-tech-test
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      -  /usr/src/app/node_modules
    environment:
      - JWT_SECRET=my_super_secret
      - HTTP_PORT=3000
